apiVersion: v1
kind: Service
metadata:
  name: url-service
  namespace: url-shortener
spec:
  selector:
    app: url-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
